# data_store.py

checklist = {
    "construction": [
        {"category": "안전관리", "item": "현장 작업자 안전모 및 안전화 착용 확인", "priority": "상", "memo": "턱끈 고정 상태까지 정밀 확인"},
        {"category": "안전관리", "item": "고소 작업 시 안전대 체결 및 생명줄 확인", "priority": "상", "memo": "2m 이상 높이 작업 시 필수"},
        {"category": "안전관리", "item": "화재 예방을 위한 소화기 비치 및 점검", "priority": "상", "memo": "용접 작업 시 불꽃 방지망 병행"},
        {"category": "공정관리", "item": "당일 작업 일보 및 투입 인원 확인", "priority": "중", "memo": "예정 공정표와 대조하여 지연 여부 체크"},
        {"category": "자재관리", "item": "반입 자재(철근, 시멘트 등) 규격 및 성적서 확인", "priority": "상", "memo": "설계 도면과 일치하는지 규격 확인"},
        {"category": "자재관리", "item": "자재 적치장 확보 및 덮개 설치 상태", "priority": "중", "memo": "비나 먼지로부터 자재 보호"},
        {"category": "기초/골조", "item": "설계 도면과 현장 먹매김 일치 여부 확인", "priority": "상", "memo": "모든 공정의 기준이 되므로 오차 엄금"},
        {"category": "기초/골조", "item": "철근 배근 간격 및 결속 상태 확인", "priority": "상", "memo": "인장 철근 위치 및 정착 길이 확인"},
        {"category": "기초/골조", "item": "거푸집 수직·수평도 및 고정 상태 점검", "priority": "상", "memo": "콘크리트 타설 시 터짐 방지"},
        {"category": "기초/골조", "item": "콘크리트 타설 전 거푸집 내 이물질 제거", "priority": "중", "memo": "강도 저하 및 공극 발생 방지"},
        {"category": "기초/골조", "item": "콘크리트 강도 및 슬럼프 테스트 실시", "priority": "상", "memo": "레미콘 규격 및 타설 시간 준수"},
        {"category": "품질검수", "item": "타설 후 양생 상태 및 살수 작업 확인", "priority": "중", "memo": "급격한 건조로 인한 균열 방지"},
        {"category": "품질검수", "item": "주요 구조부 균열 및 재료 분리 여부 검수", "priority": "상", "memo": "결함 발견 시 즉시 보수 지시"},
        {"category": "전기/설비", "item": "매립 배관 위치 및 고정 상태 확인", "priority": "중", "memo": "콘크리트 타설 중 밀림 주의"},
        {"category": "전기/설비", "item": "슬리브 설치 위치 및 규격 확인", "priority": "중", "memo": "배관 통과를 위한 구멍 확보"},
        {"category": "안전관리", "item": "가설 분전함 접지 및 누전차단기 작동 여부", "priority": "상", "memo": "감전 사고 예방을 위한 매일 점검"},
        {"category": "현장관리", "item": "비산먼지 방지망 및 세륜 시설 가동", "priority": "중", "memo": "인근 민원 발생 및 환경 법규 준수"},
        {"category": "공정관리", "item": "공정별 작업 전 TBM(툴박스미팅) 실시", "priority": "중", "memo": "작업 내용 및 위험 요인 사전 공유"},
        {"category": "자재관리", "item": "폐기물 분리 배출 및 적치 장소 관리", "priority": "하", "memo": "현장 정리 정돈은 안전의 기본"},
        {"category": "안전관리", "item": "음주 작업자 및 컨디션 불량자 투입 제한", "priority": "상", "memo": "사고 발생 위험 원천 차단"},
        {"category": "기초/골조", "item": "앵커 볼트 매립 위치 및 수평 확인", "priority": "상", "memo": "후속 공정(철골 등) 연결 부위"},
        {"category": "품질검수", "item": "층고 및 창호 개구부 치수 확인", "priority": "중", "memo": "마감 공사 시 하자 발생 방지"},
        {"category": "공정관리", "item": "야간 작업 시 충분한 조명 시설 확보", "priority": "중", "memo": "조도 부족으로 인한 안전사고 방지"},
        {"category": "품질검수", "item": "방수 공정 전 바탕면 정리 및 건조 상태", "priority": "상", "memo": "누수 하자의 가장 큰 원인 관리"},
        {"category": "현장관리", "item": "비상연락망 게시 및 응급조치 키트 확인", "priority": "상", "memo": "사고 발생 시 즉각 대응 체계 구축"},
        {"category": "서류/준비", "item": "착공 전 인허가 서류 및 신고 필증 확인", "priority": "상", "memo": "지자체별 조례 및 허가 조건 재확인"},
        {"category": "서류/준비", "item": "인근 주민 대상 사전 설명회 및 민원 대응 기록", "priority": "중", "memo": "소음/진동 민원 발생 시 근거 자료로 활용"},
        {"category": "현장관리", "item": "현장 내 가설 사무소 및 화장실 청결 상태", "priority": "하", "memo": "작업자의 능률과 현장 이미지 관리"},
        {"category": "기초/골조", "item": "타설 전 철근의 피복 두께 유지(스페이서 설치)", "priority": "상", "memo": "내구성 및 철근 부식 방지에 필수"},
        {"category": "전기/설비", "item": "배관 관통 부위 방화 구획 및 충진 확인", "priority": "상", "memo": "화재 시 연기 및 불길 확산 방지"},
        {"category": "마감공사", "item": "창호 설치 후 주위 사춤 및 방수 처리", "priority": "상", "memo": "창가 누수 하자의 주원인 점검"},
        {"category": "마감공사", "item": "바닥 타일 구배(물매) 확인 및 배수 테스트", "priority": "중", "memo": "화장실이나 발코니 물 고임 현상 방지"},
        {"category": "품질검수", "item": "주요 공정별 기록 사진 촬영 및 날짜 기록", "priority": "중", "memo": "나중에 벽 속을 확인할 수 없는 경우 대비"},
        {"category": "안전관리", "item": "중장비(포크레인, 크레인) 신호수 배치 여부", "priority": "상", "memo": "장비 작업 범위 내 일반인/작업자 출입 통제"},
        {"category": "현장관리", "item": "야간 작업 시 비상구 안내등 및 유도선 확보", "priority": "상", "memo": "정전이나 비상 상황 시 대피로 확보"}
    ],
    "travel": [
        {"category": "필수서류", "item": "여권 원본 및 사본(또는 사진) 준비", "priority": "상", "memo": "만료일 6개월 이상 남았는지 확인"},
        {"category": "필수서류", "item": "항공권 E-티켓 및 숙소 바우처 확인", "priority": "상", "memo": "오프라인에서도 볼 수 있게 다운로드"},
        {"category": "필수서류", "item": "비자 발급 여부 확인(필요 국가 시)", "priority": "상", "memo": "입국 허가서 출력 필수"},
        {"category": "필수서류", "item": "여행자 보험 가입 증명서", "priority": "중", "memo": "사고 및 질병 대비용"},
        {"category": "금융/통신", "item": "현지 화폐 환전 및 소액권 준비", "priority": "상", "memo": "팁이나 작은 상점 이용 대비"},
        {"category": "금융/통신", "item": "해외 결제 가능 카드(VISA/MASTER) 확인", "priority": "상", "memo": "카드 뒷면 서명 확인 및 분실 연락처 저장"},
        {"category": "금융/통신", "item": "유심(USIM) 또는 도시락 와이파이 예약", "priority": "상", "memo": "현지 도착 즉시 인터넷 사용 가능하게"},
        {"category": "금융/통신", "item": "현지 교통 카드(이코카, 이지카드 등) 준비", "priority": "중", "memo": "주요 도시 이동 시 필수"},
        {"category": "전자제품", "item": "보조배터리 및 충전 케이블", "priority": "상", "memo": "항공기 반입 규정 준수(기내 휴대)"},
        {"category": "전자제품", "item": "국가별 전압 멀티 어댑터(돼지코)", "priority": "중", "memo": "방문 국가 전용 플러그 모양 확인"},
        {"category": "전자제품", "item": "오프라인 구글 지도 미리 다운로드", "priority": "중", "memo": "데이터 안 터지는 지역 대비"},
        {"category": "의류/잡화", "item": "현지 날씨에 맞는 옷차림 (3~4벌)", "priority": "중", "memo": "겹쳐 입기 좋은 얇은 옷 위주"},
        {"category": "의류/잡화", "item": "편안한 여분 신발 및 슬리퍼", "priority": "중", "memo": "기내 또는 숙소 내 사용"},
        {"category": "의류/잡화", "item": "접이식 우산 또는 우비", "priority": "중", "memo": "갑작스러운 비 대비"},
        {"category": "의류/잡화", "item": "선글라스 및 자외선 차단제", "priority": "하", "memo": "현지 날씨 확인 후 준비"},
        {"category": "위생/세면", "item": "칫솔, 치약 및 면도기 세트", "priority": "중", "memo": "일부 호텔은 제공하지 않음"},
        {"category": "위생/세면", "item": "작은 용량의 샴푸, 린스, 바디워시", "priority": "하", "memo": "액체류 기내 반입 규정 준수"},
        {"category": "위생/세면", "item": "개인용 수건 (게스트하우스 이용 시)", "priority": "하", "memo": "숙소 옵션 확인"},
        {"category": "비상약", "item": "종합 감기약 및 해열제", "priority": "상", "memo": "현지 약국 이용이 어려울 수 있음"},
        {"category": "비상약", "item": "소화제 및 정로환(배탈약)", "priority": "상", "memo": "현지 음식이 맞지 않을 때 대비"},
        {"category": "비상약", "item": "개인 복용 중인 상비약", "priority": "상", "memo": "영문 처방전이 필요할 수도 있음"},
        {"category": "비상약", "item": "대역밴드 및 소독약", "priority": "중", "memo": "가벼운 상처 대비"},
        {"category": "현지정보", "item": "숙소 주소 및 전화번호 현지어 저장", "priority": "상", "memo": "택시 기사님께 보여드리기용"},
        {"category": "현지정보", "item": "방문지 주요 맛집 및 영업시간 확인", "priority": "하", "memo": "예약이 필요한 곳은 사전 예약"},
        {"category": "현지정보", "item": "현지 비상연락망 (영사관, 경찰) 저장", "priority": "상", "memo": "긴급 상황 발생 시 즉각 대응"},
        {"category": "현지정보", "item": "주요 방문지의 축제나 공휴일 일정 확인", "priority": "중", "memo": "휴무일로 인한 일정 차질 방지"},
        {"category": "보안/안전", "item": "캐리어 잠금장치 및 이름표(네임택)", "priority": "중", "memo": "수하물 분실 및 뒤바뀜 방지"},
        {"category": "보안/안전", "item": "소매치기 방지용 스프링 줄 또는 가방", "priority": "중", "memo": "치안이 불안한 지역 필수"},
        {"category": "기타", "item": "압축 파우치 (짐 부피 줄이기용)", "priority": "하", "memo": "기념품 자리를 비워두기 위해 활용"},
        {"category": "기타", "item": "비닐봉지 (세탁물 구분용)", "priority": "하", "memo": "젖은 옷이나 양말 보관"}
    ],
    "exam": [
        {"category": "D-14", "item": "전체 시험 범위 및 과목별 가중치 확인", "priority": "상", "memo": "시간 배분을 위한 전략 수립"},
        {"category": "D-14", "item": "시험 관련 공지사항(장소, 시간 변경) 확인", "priority": "상", "memo": "사이트 또는 게시판 재확인"},
        {"category": "D-10", "item": "취약 과목 집중 복습 및 개념 정리", "priority": "중", "memo": "모르는 부분 위주로 회독수 늘리기"},
        {"category": "D-10", "item": "부족한 참고서나 문제집 추가 구매", "priority": "하", "memo": "핵심 요약집 위주로 선택"},
        {"category": "D-7", "item": "기출문제 3개년치 풀이 및 오답 체크", "priority": "상", "memo": "실제 시험 난이도 및 유형 파악"},
        {"category": "D-7", "item": "시험 시간표에 맞춘 공부 시간 조정", "priority": "중", "memo": "뇌가 시험 시간에 활성화되도록 훈련"},
        {"category": "D-5", "item": "핵심 암기 사항 요약 노트 작성", "priority": "상", "memo": "시험 직전에 볼 한 페이지 분량"},
        {"category": "D-5", "item": "수험표 출력 및 규격 사진 준비", "priority": "상", "memo": "미리 준비해두어 당황 방지"},
        {"category": "D-3", "item": "시험장 교통편 및 소요 시간 시뮬레이션", "priority": "중", "memo": "당일 돌발 상황(차 막힘) 대비"},
        {"category": "D-3", "item": "수면 시간 및 식단 관리 시작", "priority": "중", "memo": "자극적인 음식 피하고 6시간 이상 숙면"},
        {"category": "D-1", "item": "신분증(주민등록증, 운전면허증 등) 확인", "priority": "상", "memo": "신분증 없으면 시험 응시 불가"},
        {"category": "D-1", "item": "컴퓨터용 싸인펜 및 여분의 검정 볼펜", "priority": "상", "memo": "잉크가 잘 나오는지 미리 테스트"},
        {"category": "D-1", "item": "수정테이프 및 지우개", "priority": "상", "memo": "답안 수정 시 필수"},
        {"category": "D-1", "item": "아날로그 손목시계 준비", "priority": "상", "memo": "스마트 워치나 전자시계 금지 확인"},
        {"category": "D-1", "item": "가방 미리 싸두기 (모든 준비물 확인)", "priority": "상", "memo": "아침에 서두르지 않도록 준비"},
        {"category": "컨디션", "item": "충분한 수분 섭취 및 안구 건조 방지", "priority": "중", "memo": "인공눈물 등 준비"},
        {"category": "컨디션", "item": "가벼운 스트레칭 및 목/어깨 근육 이완", "priority": "하", "memo": "장시간 앉아있을 대 대비"},
        {"category": "컨디션", "item": "전날 밤 마인드 컨트롤 및 긍정적 확인", "priority": "중", "memo": "긴장감 완화를 통한 실수 방지"},
        {"category": "당일", "item": "아침 식사 (가볍고 소화 잘 되는 것)", "priority": "중", "memo": "두뇌 회전을 위한 최소 영양분"},
        {"category": "당일", "item": "당 보충용 간식(초콜릿, 사탕) 지참", "priority": "하", "memo": "쉬는 시간에 섭취"},
        {"category": "당일", "item": "시험장 온도 대비용 겉옷(가디건 등)", "priority": "중", "memo": "고사장 내부 온도 조절용"},
        {"category": "당일", "item": "화장실 미리 다녀오기", "priority": "상", "memo": "시험 도중 중도 퇴실 불가 주의"},
        {"category": "당일", "item": "오답 노트 및 요약집 최종 확인", "priority": "중", "memo": "마지막 10분 암기 극대화"},
        {"category": "실전", "item": "답안지 마킹 시간 확보 (최소 5~10분)", "priority": "상", "memo": "종료 직전 마킹 실수는 치명적"},
        {"category": "실전", "item": "문제 지문 꼼꼼히 읽기 (옳은 것/틀린 것)", "priority": "상", "memo": "사소한 실수로 점수 깎임 방지"},
        {"category": "실전", "item": "모르는 문제는 과감히 넘어가기", "priority": "중", "memo": "시간 부족 방지를 위한 전략"},
        {"category": "실전", "item": "수험번호 및 성명 기재 재확인", "priority": "상", "memo": "기본 사항 미기재 시 불이익"},
        {"category": "실전", "item": "퇴실 전 소지품(지갑, 핸드폰) 챙기기",